#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Raise a NameError with a given message."""
    raise NameError(message)
